apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: enterprise-devsecops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999

      containers:
        - name: redis
          image: redis:7-alpine

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 6379

          args:
            - redis-server
            - --appendonly
            - "yes"

          volumeMounts:
            - name: redis-storage
              mountPath: /data

            - name: redis-tmp
              mountPath: /tmp

      volumes:
        - name: redis-storage
          emptyDir: {}

        - name: redis-tmp
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: enterprise-devsecops

spec:
  selector:
    app: redis

  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

  type: ClusterIP
